name: Publish anibali/pytorch:2.0.0-cuda11.8-ubuntu22.04

on:
  push:
    branches:
    - master
    paths:
    - dockerfiles/2.0.0-cuda11.8-ubuntu22.04/*
    - .github/workflows/publish_2.0.0-cuda11.8-ubuntu22.04.yml
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push image
      env:
        IMAGE_TAG: 2.0.0-cuda11.8-ubuntu22.04
      run: |
        docker build -t registry.cn-chengdu.aliyuncs.com/ai-test20230512/pytorch:$IMAGE_TAG .
        docker push registry.cn-chengdu.aliyuncs.com/ai-test20230512/pytorch:$IMAGE_TAG